Camera switching
grt192/GRT2023 pull request #44
Opened 2023-02-10 00:36 UTC by rishay-jain

2023-02-10 03:54 UTC, e3l reviewed
please squash and merge when u get around to merging so we can hide all the merge commits 🙏

2023-02-10 03:54 UTC, e3l commented on src/main/java/frc/robot/RobotContainer.java
> +    private int CameraID = 0;
why is it UpperCamel

2023-02-10 03:54 UTC, e3l commented on src/main/java/frc/robot/RobotContainer.java
> +                System.out.println("CAMERA SET TO BACK");
we can remove these if everything is working

2023-02-10 03:54 UTC, e3l commented on src/main/java/frc/robot/RobotContainer.java
> -        }, tiltedElevatorSubsystem));
pls dont just delete all our controller bindings D:

2023-02-10 03:54 UTC, e3l commented on src/main/java/frc/robot/controllers/DualJoystickDriveController.java
> +        leftUnknownButton = new JoystickButton(leftJoystick, 3);
can we know this button

2023-02-10 03:54 UTC, e3l commented on src/main/java/frc/robot/subsystems/drivetrain/BaseSwerveSubsystem.java
> +        SmartDashboard.putData("Field", cfield);
this will probably conflict with the field already being added in the `apriltag` branch. i think we can just add this feature in `apriltag`

2023-02-11 03:46 UTC, ky28059 requested changes
This contains commits from the better balancing PR and we should probably not merge this until that's tested.

2023-02-13 23:04 UTC, e3l requested changes

2023-02-13 23:04 UTC, e3l commented on src/main/java/frc/robot/subsystems/drivetrain/BaseSwerveSubsystem.java
> +        SmartDashboard.putData("Field", cfield);
field2d already exists in main

2023-02-13 23:04 UTC, e3l commented on src/main/java/frc/robot/RobotContainer.java
> +        cameraSelection = Shuffleboard.getTab("Driver Camera").add("Intake Camera", server.getSource());
maybe we can put camera logic in another class to better compoartamentalize

2023-02-19 06:09 UTC, e3l approved these changes

2023-02-19 06:09 UTC, e3l commented on src/main/java/frc/robot/RobotContainer.java
> +        shuffleboardTab.add("Auton", autonChooser)
it seems odd for all this to be on a tab called "Drivetrain"

2023-02-19 07:17 UTC, merged