offset is clamped
grt192/GRT2023 pull request #96
Opened 2023-03-16 23:13 UTC by penguin212

2023-03-16 23:34 UTC, e3l commented on src/main/java/frc/robot/subsystems/tiltedelevator/TiltedElevatorSubsystem.java
> +        if((getExtensionMeters() < EXTENSION_LIMIT_METERS || power < 0) && (getExtensionMeters() > 0 || power > 0)){
nooooooooo

2023-03-16 23:49 UTC, ky28059 requested changes

2023-03-16 23:49 UTC, ky28059 commented on src/main/java/frc/robot/subsystems/tiltedelevator/TiltedElevatorSubsystem.java
> +            this.offsetDistMeters += OFFSET_FACTOR * power;
@penguin212 what if we did a
```java
this.offsetDistMeters = MathUtil.clamp(
    offsetDistMeters = OFFSET_FACTOR,
    // distance from current extension to 0
    // distance from current extension to EXTENSION_LIMIT
);
```

2023-03-17 00:46 UTC, e3l commented on src/main/java/frc/robot/subsystems/tiltedelevator/TiltedElevatorSubsystem.java
> +            EXTENSION_LIMIT_METERS - -state.getExtension(offsetState, this.pieceGrabbed)
? double negative ???

2023-03-17 00:56 UTC, ky28059 commented on src/main/java/frc/robot/subsystems/tiltedelevator/TiltedElevatorSubsystem.java
> +            this.offsetDistMeters += OFFSET_FACTOR * power;
I realized I did a typo when writing out this code block in GitHub, @penguin212 can you update the `offsetDistMeters =` to a `offsetDistMeters +`? It doesn't make sense to set the offset to the offset factor 😔

2023-03-17 21:59 UTC, merged